// Product data shared by index.html and catalogue.html. Prices in KES. Edit here to change both pages.
window.CATEGORY_ORDER=["Basin Mixers & Taps", "Kitchen Mixers & Sink Taps", "Shower Sets", "Bath Mixers", "Concealed Mixers", "Toilets & Sanitary Ware", "Kitchen Sinks", "Bathroom Accessories", "Vanity Cabinets & Mirrors", "Angle Valves & Filters", "Drainers & Hoses"];
window.FEATURED=["8011", "8014H", "8014H-2", "8016C", "3016K", "3004C", "6001", "LL9013-3C"];
window.PRODUCTS=[
{"code": "GJ8200S", "name": "Bathroom Accessories Set", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/0344668727.jpg", "price": 4900},
{"code": "GJ8200H", "name": "Bathroom Accessories Set", "cat": "Bathroom Accessories", "finish": "Grey", "img": "img/9ea56898e6.jpg", "price": 5670},
{"code": "GJ8200K", "name": "Bathroom Accessories Set", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/c844975476.jpg", "price": 5670},
{"code": "GJ8100S", "name": "Bathroom Accessories Set", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/52b8f6c7e5.jpg", "price": 5180},
{"code": "GJ8100H", "name": "Bathroom Accessories Set", "cat": "Bathroom Accessories", "finish": "Grey", "img": "img/ea8e96bf3f.jpg", "price": 5670},
{"code": "GJ8100K", "name": "Bathroom Accessories Set", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/8404b3c3af.jpg", "price": 5670},
{"code": "GJ8201S", "name": "Single Towel Rack", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/59de0cdb30.jpg", "price": 700},
{"code": "GJ8201H", "name": "Single Towel Rack", "cat": "Bathroom Accessories", "finish": "Grey", "img": "img/59de0cdb30.jpg", "price": 700},
{"code": "GJ8201K", "name": "Single Towel Rack", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/59de0cdb30.jpg", "price": 700},
{"code": "GJ602S", "name": "Double Towel Rack", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/b2f9295e9f.jpg", "price": 1470},
{"code": "GJ602G", "name": "Double Towel Rack", "cat": "Bathroom Accessories", "finish": "Gold", "img": "img/b2f9295e9f.jpg", "price": 1470},
{"code": "GJ602H", "name": "Double Towel Rack", "cat": "Bathroom Accessories", "finish": "Grey", "img": "img/b2f9295e9f.jpg", "price": 1470},
{"code": "GJ602K", "name": "Double Towel Rack", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/b2f9295e9f.jpg", "price": 1470},
{"code": "GJ702", "name": "Single Towel Rack (70/90cm)", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/b4996d9714.jpg", "size": "70cm", "price": 910},
{"code": "GJ902", "name": "Single Towel Rack (70/90cm)", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/b4996d9714.jpg", "size": "90cm", "price": 980},
{"code": "GJ8210S", "name": "Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/4a3ad12c8f.jpg", "price": 660},
{"code": "GJ8210H", "name": "Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Grey", "img": "img/4a3ad12c8f.jpg", "price": 660},
{"code": "GJ8210K", "name": "Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/4a3ad12c8f.jpg", "price": 660},
{"code": "GJ8211S", "name": "Double Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/825112bdac.jpg", "price": 900},
{"code": "GJ8211H", "name": "Double Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Grey", "img": "img/825112bdac.jpg", "price": 940},
{"code": "GJ8211K", "name": "Double Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/825112bdac.jpg", "price": 940},
{"code": "GJ8213S", "name": "Toilet Brush Holder", "cat": "Bathroom Accessories", "finish": "Silver", "img": "img/a52c1db29f.jpg", "price": 1470},
{"code": "GJ8213H", "name": "Toilet Brush Holder", "cat": "Bathroom Accessories", "finish": "Grey", "img": "img/69a392faf8.jpg", "price": 1470},
{"code": "GJ8213K", "name": "Toilet Brush Holder", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/1cb4a0ade0.jpg", "price": 1470},
{"code": "GJR822C", "name": "Toothbrush Holder Wall Mounted", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/95609fb96b.jpg", "price": 930},
{"code": "GJR822K", "name": "Toothbrush Holder Wall Mounted", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/90dfdc7b77.jpg", "price": 930},
{"code": "GJR823C", "name": "Double Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/5cd1598a9e.jpg", "price": 1190},
{"code": "GJR823K", "name": "Double Toothbrush Holder", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/f18eb95daf.jpg", "price": 1190},
{"code": "GJ824C", "name": "Toothbrush Holder Classic", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/cc031b0bc6.jpg", "price": 1000},
{"code": "GJ824K", "name": "Toothbrush Holder Classic", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/ac9b6d3e2f.jpg", "price": 1000},
{"code": "GJ825C", "name": "Double Tooth Brush Holder", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/1f079713ed.jpg", "price": 1360},
{"code": "GJ825K", "name": "Double Tooth Brush Holder", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/4e33df3d9d.jpg", "price": 1360},
{"code": "GJ8801", "name": "Towel Rail", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/1885f3a4d2.jpg", "price": 2520},
{"code": "GJ8802K", "name": "Towel Rail", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/0db9cc50d1.jpg", "price": 2660},
{"code": "GJ1052C-4", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Mirror Finish", "img": "img/923256c0d6.jpg", "price": 480},
{"code": "GJ1052C-5", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Mirror Finish", "img": "img/923256c0d6.jpg", "price": 560},
{"code": "GJ1052K-4", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/205a9e14fb.jpg", "price": 420},
{"code": "GJ1052K-5", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/205a9e14fb.jpg", "price": 520},
{"code": "GJS6603", "name": "Soap Dish Holder", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/cc99d3b3c4.jpg", "price": 270},
{"code": "GJS6603K", "name": "Soap Dish Holder", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/68a3a7d628.jpg", "price": 270},
{"code": "GJ6604C", "name": "Soap Dish", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/3fb7ec1716.jpg", "price": 590},
{"code": "GJ6604K", "name": "Soap Dish", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/d634501ee0.jpg", "price": 590},
{"code": "GJS6601", "name": "Tissue Holder Covered", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/54ac799d25.jpg", "price": 660},
{"code": "GJS6601K", "name": "Tissue Holder Covered", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/583d6e432b.jpg", "price": 730},
{"code": "GJS6602", "name": "Tissue Holder", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/d3eb28a843.jpg", "price": 610},
{"code": "GJS6605C", "name": "Tissue Holder", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/6179a9b3c7.jpg", "price": 700},
{"code": "GJS6605K", "name": "Tissue Holder", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/4278c4670b.jpg", "price": 700},
{"code": "GJS6606C", "name": "Towel Ring", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/1b0e712a94.jpg"},
{"code": "GJS6606K", "name": "Towel Ring", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/586ccec738.jpg", "price": 820},
{"code": "GJS6610C", "name": "Corner Basket", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/77b43927e7.jpg", "price": 1100},
{"code": "GJS6610K", "name": "Corner Basket", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/5aa5ed8085.jpg", "price": 1100},
{"code": "GJ6611C", "name": "Double Corner Basket", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/f5ff3cb880.jpg", "price": 2030},
{"code": "GJ6611K", "name": "Double Corner Basket", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/28b6f4bfae.jpg", "price": 2240},
{"code": "GJ6612C", "name": "Double Corner Basket", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/ccc7f244d9.jpg", "price": 2240},
{"code": "GJ6612K", "name": "Double Corner Basket", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/b1f910e602.jpg", "price": 2380},
{"code": "TX27-1W", "name": "Soap Dispenser 500ml", "cat": "Bathroom Accessories", "finish": "White", "img": "img/1d7fde8698.jpg", "size": "500ml", "price": 560},
{"code": "TX29-1W", "name": "Soap Dispenser", "cat": "Bathroom Accessories", "finish": "White", "img": "img/e08ef608fd.jpg", "size": "350ml", "price": 590},
{"code": "TX33-1B", "name": "Soap Dispenser 400ml", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/22728c8f7e.jpg", "size": "400ml", "price": 590},
{"code": "TX35BK", "name": "Soap Dispenser", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/b1564ca266.jpg", "size": "1000ml", "price": 1240},
{"code": "TX35W", "name": "Soap Dispenser", "cat": "Bathroom Accessories", "finish": "White", "img": "img/6007adbfe5.jpg", "size": "1000ml", "price": 1240},
{"code": "HD113", "name": "Automatic Hand Dryer", "cat": "Bathroom Accessories", "finish": "White", "img": "img/a937a3cc4b.jpg"},
{"code": "3011C", "name": "Basin Mixer Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/33419d71ee.jpg"},
{"code": "3002C", "name": "Basin Mixer Modern", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/2e52e3359f.jpg"},
{"code": "3002", "name": "Basin Mixer Modern", "cat": "Basin Mixers & Taps", "finish": "Brushed Nickel", "img": "img/6aad90b07a.jpg", "price": 1330, "best": 1},
{"code": "3002K", "name": "Basin Mixer Modern", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/d11c76b251.jpg", "price": 1400, "best": 1},
{"code": "3002H", "name": "Basin Mixer Modern", "cat": "Basin Mixers & Taps", "finish": "Grey", "img": "img/821d558e5f.jpg", "price": 1400, "best": 1},
{"code": "3003C", "name": "Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/c005fa51b8.jpg"},
{"code": "3015C", "name": "Basin Mixer Slanted Spout", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/ee03d8b40f.jpg", "price": 2240, "best": 1},
{"code": "3015H", "name": "Basin Mixer Slanted Spout", "cat": "Basin Mixers & Taps", "finish": "Grey", "img": "img/d09b6612c2.jpg", "price": 2240, "best": 1},
{"code": "3015K", "name": "Basin Mixer Slanted Spout", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/6049e24c12.jpg", "price": 2240, "best": 1},
{"code": "3016C", "name": "Basin Mixer Linear", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/3e5df5b810.jpg", "price": 2240, "best": 1},
{"code": "3016H", "name": "Basin Mixer Linear", "cat": "Basin Mixers & Taps", "finish": "Grey", "img": "img/d5f3ecedd6.jpg", "price": 2240, "best": 1},
{"code": "3016K", "name": "Basin Mixer Linear", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/f5c6975cd9.jpg", "price": 2240, "best": 1},
{"code": "3009C", "name": "Basin Mixer Flat Arch", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/6aec1e6b7c.jpg"},
{"code": "3009K", "name": "Basin Mixer Flat Arch", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/2b9aac2620.jpg", "price": 1400, "best": 1},
{"code": "3009H", "name": "Basin Mixer Flat Arch", "cat": "Basin Mixers & Taps", "finish": "Grey", "img": "img/a0121f3b87.jpg", "price": 1400, "best": 1},
{"code": "3014", "name": "Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "Brushed Nickel", "img": "img/b8e6635bf8.jpg", "price": 1820, "best": 1},
{"code": "3014K", "name": "Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/64e8a71eb9.jpg", "price": 1820, "best": 1},
{"code": "3020TC", "name": "Tall Basin Mixer (Countertop)", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/b6a4c9293b.jpg"},
{"code": "3019TC", "name": "Tall Basin Mixer High Arc", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/3394e919de.jpg"},
{"code": "3019TK", "name": "Tall Basin Mixer High Arc", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/d8fae27211.jpg", "price": 2660, "best": 1},
{"code": "3019TH", "name": "Basin Mixer (Tall)", "cat": "Basin Mixers & Taps", "finish": "Brushed Nickel", "img": "img/048b28495e.jpg", "price": 2660, "best": 1},
{"code": "3021TC", "name": "Basin Mixer (Tall)", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/21b278bc93.jpg"},
{"code": "3022C", "name": "Basin Mixer (Tall)", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/d76ecf90c3.jpg"},
{"code": "3022TK", "name": "Basin Mixer (Tall)", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/94af89127c.jpg"},
{"code": "3017C", "name": "Pull-Out Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/b63024aedb.jpg", "price": 1820, "best": 1},
{"code": "3017K", "name": "Pull-Out Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/9e20b1406a.jpg", "price": 1820, "best": 1},
{"code": "2201", "name": "Single Cold Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Brushed Nickel", "img": "img/fa8abbfc52.jpg", "price": 600, "best": 1},
{"code": "2201K", "name": "Single Cold Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/71b88bfbb4.jpg", "price": 660, "best": 1},
{"code": "2203", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Brushed Nickel", "img": "img/f170e924cd.jpg", "price": 600, "best": 1},
{"code": "2203K", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/5d32c82dfa.jpg", "price": 660, "best": 1},
{"code": "2204C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/1f60b404a6.jpg"},
{"code": "2205C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/f545614499.jpg"},
{"code": "2206C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/71922ba834.jpg"},
{"code": "2207C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/cf4a36aa8e.jpg"},
{"code": "2208C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/483da0420c.jpg"},
{"code": "2310C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/7efee9647e.jpg"},
{"code": "2311C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/ef33a28a82.jpg"},
{"code": "2312C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/73b950da41.jpg"},
{"code": "2313C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/b308fb1fee.jpg"},
{"code": "2314C", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/5b035f4cc2.jpg"},
{"code": "2314K", "name": "Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/a57f01790a.jpg"},
{"code": "2314TC", "name": "Tall Pillar Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/7b2b193a15.jpg"},
{"code": "2314TK", "name": "Tall Pillar Basin Tap", "cat": "Basin Mixers & Taps", "finish": "Black", "img": "img/b74a1e6468.jpg"},
{"code": "6001", "name": "Gooseneck Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/b26b24543a.jpg", "price": 1540, "best": 1},
{"code": "6001C", "name": "Gooseneck Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/dc14c56ed7.jpg", "price": 1680, "best": 1},
{"code": "6003", "name": "Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/78f61e78b2.jpg", "price": 1540, "best": 1},
{"code": "6003C", "name": "Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/794c50b9da.jpg", "price": 1680, "best": 1},
{"code": "6023", "name": "Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/e5b5d75829.jpg", "price": 2100, "best": 1},
{"code": "6023K", "name": "Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/551fa91d13.jpg", "price": 2240, "best": 1},
{"code": "6016C", "name": "Pull-Out Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/2b49c084d7.jpg", "price": 3220, "best": 1},
{"code": "6016K", "name": "Pull-Out Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/ba95eaa4b1.jpg", "price": 3220, "best": 1},
{"code": "6016H", "name": "Pull-Out Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Grey", "img": "img/f9cabe0c6e.jpg", "price": 3220, "best": 1},
{"code": "6018K", "name": "Chef Style Pull-Out Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/8a1609a7dd.jpg", "price": 3780, "best": 1},
{"code": "6018H", "name": "Kitchen Mixer (Pull-out)", "cat": "Kitchen Mixers & Sink Taps", "finish": "Grey", "img": "img/7dbff1a916.jpg", "price": 3780, "best": 1},
{"code": "6019C", "name": "Commercial Spring Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/2a1898741a.jpg", "price": 4480, "best": 1},
{"code": "6019K", "name": "Commercial Spring Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/741cd6bef9.jpg", "price": 4480, "best": 1},
{"code": "6020C", "name": "Heavy Spring Pull-Down Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/1629e412e5.jpg", "price": 5040, "best": 1},
{"code": "6020K", "name": "Kitchen Mixer (Spring)", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/7c319b3d02.jpg", "price": 5040, "best": 1},
{"code": "6021C", "name": "Wall Mounted Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/e1476a4951.jpg", "price": 2100, "best": 1},
{"code": "6022C", "name": "Wall Mounted Kitchen Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/2e44556436.jpg", "price": 2520, "best": 1},
{"code": "W2006", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/cfb11918e7.jpg", "price": 2170, "best": 1},
{"code": "W2001", "name": "Swivel Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/7e73f853ee.jpg", "price": 660, "best": 1},
{"code": "W2001K", "name": "Swivel Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/fbda2ba322.jpg", "price": 660, "best": 1},
{"code": "W2002", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/0b04b8a816.jpg", "price": 820, "best": 1},
{"code": "W2012C", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/d570364148.jpg"},
{"code": "W2003", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/0719791e7a.jpg", "price": 820, "best": 1},
{"code": "W2004", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/02d61c192e.jpg", "price": 910, "best": 1},
{"code": "W2008", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/d144d77209.jpg", "price": 1240, "best": 1},
{"code": "W2008K", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/f2ca5fcd0b.jpg", "price": 1240, "best": 1},
{"code": "W2010C", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/4b24418760.jpg"},
{"code": "W2013C", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/8359de47ca.jpg"},
{"code": "W2014C", "name": "Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/7b04b68cf8.jpg"},
{"code": "W2005C", "name": "Foldable Window Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/f4ceea92fa.jpg", "price": 2800, "best": 1},
{"code": "W2005H", "name": "Foldable Window Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Grey", "img": "img/27605af01e.jpg", "price": 2800, "best": 1},
{"code": "W2005K", "name": "Foldable Window Sink Tap", "cat": "Kitchen Mixers & Sink Taps", "finish": "Black", "img": "img/f5f229ed47.jpg", "price": 2800, "best": 1},
{"code": "W2005S", "name": "Sink Tap (Foldable)", "cat": "Kitchen Mixers & Sink Taps", "finish": "Brushed Nickel", "img": "img/fa67772166.jpg", "price": 2800, "best": 1},
{"code": "6045", "name": "Single Bowl Sink (60x45cm)", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/81fac2bff7.jpg", "size": "60x45cm", "price": 5600},
{"code": "6045K", "name": "Single Bowl Sink (60x45cm)", "cat": "Kitchen Sinks", "finish": "Black", "img": "img/8aae3d9eee.jpg", "size": "60x45cm", "price": 6300},
{"code": "7843", "name": "Double Bowl Sink (78x43cm)", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/ebe9869bef.jpg", "size": "78x43cm", "price": 7700},
{"code": "7843K", "name": "Double Bowl Sink (78x43cm)", "cat": "Kitchen Sinks", "finish": "Black", "img": "img/e4f9ba230c.jpg", "size": "78x43cm", "price": 8400},
{"code": "7546-5K", "name": "Waterfall 5-Key Piano Sink (75x46cm)", "cat": "Kitchen Sinks", "finish": "Black", "img": "img/9b0ff03f12.jpg", "size": "75x46cm", "price": 22260},
{"code": "7546-4K", "name": "Waterfall 4-Key Piano Sink (75x46cm)", "cat": "Kitchen Sinks", "finish": "Black", "img": "img/350efd0118.jpg", "size": "75x46cm", "price": 20580},
{"code": "7546K", "name": "Modern Single Sink (75x46cm)", "cat": "Kitchen Sinks", "finish": "Black", "img": "img/bd87fd1b32.jpg", "size": "75x46cm", "price": 16800},
{"code": "5040LS", "name": "Sink", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/bbe2912939.jpg", "size": "50x40cm", "price": 1680},
{"code": "7843LS", "name": "Double Sink", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/4c9482d999.jpg", "size": "78x43cm", "price": 3500},
{"code": "7540LS", "name": "Single Sink with Drainer (75x40cm)", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/667d651fa1.jpg", "size": "75x40cm"},
{"code": "9643LS", "name": "Sink with Drainer (96x43cm)", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/86096e155e.jpg", "size": "96x43cm", "price": 2380},
{"code": "10050LS", "name": "Large Sink with Drainer (100x50cm)", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/123c159a7b.jpg", "size": "100x50cm", "price": 3780},
{"code": "12050-2LS", "name": "Double Bowl Sink + Drainer (120x50cm)", "cat": "Kitchen Sinks", "finish": "Brushed Nickel", "img": "img/8db629a75c.jpg", "size": "120x50cm", "price": 6720},
{"code": "Sink waste-1", "name": "Sink Waste (Single)", "cat": "Kitchen Sinks", "finish": "Grey", "img": "img/9e671c9726.jpg"},
{"code": "Sink waste-2", "name": "Sink Waste (Double)", "cat": "Kitchen Sinks", "finish": "Grey", "img": "img/2222bcecf6.jpg"},
{"code": "8011", "name": "Exposed Shower Column", "cat": "Shower Sets", "finish": "Brushed Nickel", "img": "img/a39541aaf0.jpg", "price": 7000, "best": 1},
{"code": "8011K", "name": "Exposed Shower Column", "cat": "Shower Sets", "finish": "Black", "img": "img/4e21627a15.jpg", "price": 7140, "best": 1},
{"code": "8012C", "name": "Exposed Shower Column", "cat": "Shower Sets", "finish": "Chrome", "img": "img/4a3c1d5119.jpg"},
{"code": "8015C", "name": "Rain Shower System", "cat": "Shower Sets", "finish": "Chrome", "img": "img/2a8b573320.jpg"},
{"code": "8035C", "name": "Shower Set", "cat": "Shower Sets", "finish": "Chrome", "img": "img/e2bb8546f8.jpg"},
{"code": "8018C", "name": "Thermostatic Rain Shower", "cat": "Shower Sets", "finish": "Chrome", "img": "img/3ca154e1f1.jpg"},
{"code": "8018K", "name": "Thermostatic Rain Shower", "cat": "Shower Sets", "finish": "Black", "img": "img/1d06451584.jpg"},
{"code": "8014H", "name": "4-in-1 Piano Button Shower System", "cat": "Shower Sets", "finish": "Grey", "img": "img/346374b7ab.jpg", "price": 5040, "best": 1},
{"code": "8014K", "name": "4-in-1 Piano Button Shower System", "cat": "Shower Sets", "finish": "Black", "img": "img/9d76fe4e3c.jpg", "price": 5040, "best": 1},
{"code": "8014H-2", "name": "Shower Set, 4-in-1 Piano Button", "cat": "Shower Sets", "finish": "Grey", "img": "img/f5b57833d4.jpg", "price": 6020, "best": 1},
{"code": "8014K-2", "name": "Shower Set, 4-in-1 Piano Button", "cat": "Shower Sets", "finish": "Black", "img": "img/1023f8b90d.jpg", "price": 6020, "best": 1},
{"code": "8016C", "name": "4-in-1 Piano Button Shower Set", "cat": "Shower Sets", "finish": "Chrome", "img": "img/a580369a7e.jpg", "price": 10360, "best": 1},
{"code": "8016K", "name": "4-in-1 Piano Button Shower Set", "cat": "Shower Sets", "finish": "Black", "img": "img/44cfebd241.jpg", "price": 10360, "best": 1},
{"code": "8016H", "name": "4-in-1 Piano Button Shower Set", "cat": "Shower Sets", "finish": "Grey", "img": "img/59155bc37e.jpg", "price": 10360, "best": 1},
{"code": "8017C", "name": "Shower Set, 4-in-1 Piano Button", "cat": "Shower Sets", "finish": "Chrome", "img": "img/ba00fa64ca.jpg", "price": 8260, "best": 1},
{"code": "8017K", "name": "Shower Set, 4-in-1 Piano Button", "cat": "Shower Sets", "finish": "Black", "img": "img/62a3a028ec.jpg", "price": 8260, "best": 1},
{"code": "8017H", "name": "Shower Set, 4-in-1 Piano Button", "cat": "Shower Sets", "finish": "Grey", "img": "img/630b98a8a7.jpg", "price": 8260, "best": 1},
{"code": "8021C", "name": "Digital LED Piano Shower System", "cat": "Shower Sets", "finish": "Chrome", "img": "img/32729dbc3b.jpg", "price": 10360, "best": 1},
{"code": "8021K", "name": "Digital LED Piano Shower System", "cat": "Shower Sets", "finish": "Black", "img": "img/1b2bca48d0.jpg", "price": 10360, "best": 1},
{"code": "8021H", "name": "Digital LED Piano Shower System", "cat": "Shower Sets", "finish": "Grey", "img": "img/5aaccadf4e.jpg", "price": 10360, "best": 1},
{"code": "8033C", "name": "Shower Set, 4-in-1 Piano Button, Digital Display & LED", "cat": "Shower Sets", "finish": "Chrome", "img": "img/4d3ae176f0.jpg"},
{"code": "8033K", "name": "Digital Hydro-Powered LED Shower", "cat": "Shower Sets", "finish": "Black", "img": "img/6c49824fbb.jpg"},
{"code": "8033H", "name": "Digital Hydro-Powered LED Shower", "cat": "Shower Sets", "finish": "Grey", "img": "img/03c8ae61b4.jpg"},
{"code": "8034C", "name": "Piano Key Digital Rain Shower", "cat": "Shower Sets", "finish": "Chrome", "img": "img/27d09a963f.jpg"},
{"code": "8034K", "name": "Piano Key Digital Rain Shower", "cat": "Shower Sets", "finish": "Black", "img": "img/1979a8e5d3.jpg", "price": 13300, "best": 1},
{"code": "8034H", "name": "Piano Key Digital Rain Shower", "cat": "Shower Sets", "finish": "Grey", "img": "img/5e71daa31e.jpg", "price": 13300, "best": 1},
{"code": "8023H", "name": "Shower Set, 4-in-1 Piano Button, Digital Display & LED", "cat": "Shower Sets", "finish": "Grey", "img": "img/5cabbca40e.jpg", "price": 12880, "best": 1},
{"code": "8031H", "name": "Shower Set, 4-in-1 Piano Button, Digital Display & LED", "cat": "Shower Sets", "finish": "Grey", "img": "img/c093a3e897.jpg", "price": 10640, "best": 1},
{"code": "8302", "name": "Exposed Bath Tub Mixer", "cat": "Bath Mixers", "finish": "Brushed Nickel", "img": "img/768853002c.jpg", "price": 3220, "best": 1},
{"code": "8302K", "name": "Exposed Bath Tub Mixer", "cat": "Bath Mixers", "finish": "Black", "img": "img/327ea8f172.jpg", "price": 3220, "best": 1},
{"code": "8303", "name": "Bath Mixer", "cat": "Bath Mixers", "finish": "Brushed Nickel", "img": "img/0595a6fab6.jpg", "price": 2800, "best": 1},
{"code": "8304C", "name": "Bath Mixer with Hand Shower", "cat": "Bath Mixers", "finish": "Chrome", "img": "img/adacbe961c.jpg"},
{"code": "8304H", "name": "Bath Mixer with Hand Shower", "cat": "Bath Mixers", "finish": "Grey", "img": "img/9ad942c33d.jpg"},
{"code": "8304K", "name": "Bath Mixer with Hand Shower", "cat": "Bath Mixers", "finish": "Black", "img": "img/d6d0f1bb75.jpg"},
{"code": "8301C", "name": "Bath Mixer", "cat": "Bath Mixers", "finish": "Chrome", "img": "img/24308c86e6.jpg", "price": 2940, "best": 1},
{"code": "8301K", "name": "Bath Mixer", "cat": "Bath Mixers", "finish": "Black", "img": "img/64e8fa7fe3.jpg", "price": 2940, "best": 1},
{"code": "8305C", "name": "Bath Mixer with Sliding Rail", "cat": "Bath Mixers", "finish": "Chrome", "img": "img/48b05ff3fc.jpg"},
{"code": "8305H", "name": "Bath Mixer With Sliding Bar", "cat": "Bath Mixers", "finish": "Grey", "img": "img/8410de0c8a.jpg"},
{"code": "8305K", "name": "Bath Mixer With Sliding Bar", "cat": "Bath Mixers", "finish": "Black", "img": "img/938bdff256.jpg"},
{"code": "8306C", "name": "3-in-1 Piano Digital LED Bath Mixer", "cat": "Bath Mixers", "finish": "Chrome", "img": "img/fc167fa8ac.jpg", "price": 7700, "best": 1},
{"code": "8306H", "name": "3-in-1 Piano Digital LED Bath Mixer", "cat": "Bath Mixers", "finish": "Grey", "img": "img/786c3d5233.jpg", "price": 7700, "best": 1},
{"code": "8306K", "name": "3-in-1 Piano Digital LED Bath Mixer", "cat": "Bath Mixers", "finish": "Black", "img": "img/c90b8be009.jpg", "price": 7700, "best": 1},
{"code": "8401C", "name": "Freestanding Bath Mixer Tap", "cat": "Bath Mixers", "finish": "Chrome", "img": "img/fe9473c1bb.jpg", "price": 14280, "best": 1},
{"code": "8401K", "name": "Freestanding Bath Mixer Tap", "cat": "Bath Mixers", "finish": "Black", "img": "img/fe934f6aa9.jpg", "price": 14280, "best": 1},
{"code": "8402C", "name": "Standing Bath Spout & Shower", "cat": "Bath Mixers", "finish": "Chrome", "img": "img/f9aeb1556f.jpg", "price": 18900, "best": 1},
{"code": "8402K", "name": "Standing Bath Spout & Shower", "cat": "Bath Mixers", "finish": "Black", "img": "img/8123fbb9de.jpg", "price": 18900, "best": 1},
{"code": "LL9011C", "name": "Concealed Shower Valve Mixer", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/2582d66a28.jpg"},
{"code": "LL9011K", "name": "Concealed Shower Valve Mixer", "cat": "Concealed Mixers", "finish": "Black", "img": "img/a0723b0940.jpg"},
{"code": "LL9014C", "name": "Concealed Shower Mixer Set", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/4eb3b33c46.jpg"},
{"code": "LL9014K", "name": "Concealed Shower Mixer Set", "cat": "Concealed Mixers", "finish": "Black", "img": "img/19d4e64ee8.jpg"},
{"code": "LL9012C", "name": "Concealed Shower Mixer", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/2a0452dd77.jpg", "price": 6580, "best": 1},
{"code": "LL9012K", "name": "Concealed Shower Mixer", "cat": "Concealed Mixers", "finish": "Black", "img": "img/af68061eb8.jpg", "price": 6580, "best": 1},
{"code": "LL9013-3C", "name": "3-Way Concealed Diverter Mixer", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/f7be92dabc.jpg", "price": 10220, "best": 1},
{"code": "LL9013-3H", "name": "3-Way Concealed Diverter Mixer", "cat": "Concealed Mixers", "finish": "Grey", "img": "img/c70b4c88bb.jpg", "price": 11060, "best": 1},
{"code": "LL9013-3K", "name": "3-Way Concealed Diverter Mixer", "cat": "Concealed Mixers", "finish": "Black", "img": "img/531b0efade.jpg", "price": 10220, "best": 1},
{"code": "LL9017-3C", "name": "Concealed Shower Mixer", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/54016ab4fb.jpg", "price": 19600, "best": 1},
{"code": "LL9017-3K", "name": "Concealed Shower Mixer", "cat": "Concealed Mixers", "finish": "Black", "img": "img/3c5da21a90.jpg", "price": 19600, "best": 1},
{"code": "LL3004C", "name": "Concealed Built-in Mixer", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/464163098a.jpg"},
{"code": "LL3004H", "name": "Concealed Built-in Mixer", "cat": "Concealed Mixers", "finish": "Grey", "img": "img/ae3ea267b9.jpg"},
{"code": "LL3004K", "name": "Concealed Built-in Mixer", "cat": "Concealed Mixers", "finish": "Black", "img": "img/6887025150.jpg"},
{"code": "LL3009C", "name": "Wall-Mounted Concealed Basin Mixer", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/6bd96075e1.jpg", "price": 4620, "best": 1},
{"code": "LL3009H", "name": "Wall-Mounted Concealed Basin Mixer", "cat": "Concealed Mixers", "finish": "Grey", "img": "img/a430640050.jpg"},
{"code": "LL3009K", "name": "Wall-Mounted Concealed Basin Mixer", "cat": "Concealed Mixers", "finish": "Black", "img": "img/f2e4c567cd.jpg", "price": 4620, "best": 1},
{"code": "9015C", "name": "Dual-Function Angle Valve 1/2\"", "cat": "Angle Valves & Filters", "finish": "Chrome", "img": "img/6473a5dee4.jpg", "price": 630},
{"code": "9015K", "name": "Dual-Function Angle Valve 1/2\"", "cat": "Angle Valves & Filters", "finish": "Black", "img": "img/2daf2f77c4.jpg", "price": 630},
{"code": "9008", "name": "Heavy Brass Angle Valve", "cat": "Angle Valves & Filters", "finish": "Brushed Nickel", "img": "img/4b4d54b61b.jpg", "price": 210},
{"code": "9008K", "name": "Heavy Brass Angle Valve", "cat": "Angle Valves & Filters", "finish": "Black", "img": "img/0bc9a0a8cd.jpg", "price": 240},
{"code": "9012", "name": "Angle Valve", "cat": "Angle Valves & Filters", "finish": "Brushed Nickel", "img": "img/787cb61fc4.jpg", "price": 260},
{"code": "9013-1", "name": "Angle Valve", "cat": "Angle Valves & Filters", "finish": "Brushed Nickel", "img": "img/29c521de59.jpg", "price": 170},
{"code": "9013-2", "name": "Angle Valve", "cat": "Angle Valves & Filters", "finish": "Brushed Nickel", "img": "img/fd37f592cb.jpg", "price": 170},
{"code": "9017C", "name": "Angle Valve", "cat": "Angle Valves & Filters", "finish": "Chrome", "img": "img/1fb05504f1.jpg", "price": 260},
{"code": "9018C", "name": "Angle Valve", "cat": "Angle Valves & Filters", "finish": "Chrome", "img": "img/8643eab0cb.jpg", "price": 260},
{"code": "9005", "name": "Long Extended Wall Bib Tap", "cat": "Angle Valves & Filters", "finish": "Brushed Nickel", "img": "img/145a42e42d.jpg", "price": 660},
{"code": "9007", "name": "Water Tap", "cat": "Angle Valves & Filters", "finish": "Brushed Nickel", "img": "img/90eedbc0d5.jpg", "price": 450},
{"code": "9611C", "name": "Single Water Tap", "cat": "Angle Valves & Filters", "finish": "Chrome", "img": "img/0851c9f639.jpg"},
{"code": "9611K", "name": "Single Water Tap", "cat": "Angle Valves & Filters", "finish": "Black", "img": "img/c579a90c5e.jpg"},
{"code": "9612C", "name": "Long Spout Water Tap", "cat": "Angle Valves & Filters", "finish": "Chrome", "img": "img/b98050f0f2.jpg"},
{"code": "9612K", "name": "Long Spout Water Tap", "cat": "Angle Valves & Filters", "finish": "Black", "img": "img/ded75e9307.jpg"},
{"code": "WF13A", "name": "Single Water Filter Housing 3/4\" & 1\"", "cat": "Angle Valves & Filters", "finish": "Blue/Clear", "img": "img/a1c122c05d.jpg", "size": "3/4\"", "price": 2100},
{"code": "WF13B", "name": "Single Water Filter Housing 3/4\" & 1\"", "cat": "Angle Valves & Filters", "finish": "Blue/Clear", "img": "img/a1c122c05d.jpg", "size": "1\"", "price": 2100},
{"code": "WF14A", "name": "Double Water Filter Housing Unit", "cat": "Angle Valves & Filters", "finish": "Standard", "img": "img/cca1106136.jpg", "size": "3/4\"", "price": 3500},
{"code": "WF14B", "name": "Double Water Filter Housing Unit", "cat": "Angle Valves & Filters", "finish": "Standard", "img": "img/cca1106136.jpg", "size": "1\"", "price": 3500},
{"code": "PP100", "name": "Sediment Polypropylene Filter Cartridge", "cat": "Angle Valves & Filters", "finish": "100g", "img": "img/4bc20fa0e6.jpg", "size": "100g", "price": 200},
{"code": "XR53", "name": "Filter Cartridge", "cat": "Angle Valves & Filters", "finish": "", "img": "img/6107108762.jpg", "size": "150g", "price": 260},
{"code": "CTO10A", "name": "Activated Carbon Block Filter Cartridge", "cat": "Angle Valves & Filters", "finish": "400g", "img": "img/d048c76273.jpg", "size": "400g", "price": 410},
{"code": "UDF10A", "name": "Filter Cartridge", "cat": "Angle Valves & Filters", "finish": "", "img": "img/dcaae13187.jpg", "size": "400g", "price": 410},
{"code": "4336-1", "name": "Compact Vanity Cabinet (43x36cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Modern", "img": "img/1a496b1407.jpg", "size": "43x36cm", "price": 6720},
{"code": "5037-1", "name": "Wall-Hung Vanity (50x37cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Modern", "img": "img/9ce8edc6e9.jpg", "size": "50x37cm"},
{"code": "5036-2", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/4475a16e6b.jpg", "size": "50cm", "price": 16800},
{"code": "5036-4", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/44e5ef6003.jpg", "size": "50cm"},
{"code": "603-60", "name": "Bathroom Vanity Set (60cm & 80cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Wood Finish", "img": "img/d8e17fa5a0.jpg", "size": "60cm & 80cm", "price": 25200},
{"code": "608-80", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/e2a4b4deb4.jpg", "size": "60cm & 80cm", "price": 25200},
{"code": "2001-80", "name": "Natural Sintered Stone Vanity (80cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Stone Grey", "img": "img/49f4b6cbbe.jpg", "size": "80cm", "price": 32200},
{"code": "2001H-120", "name": "Double Basin Master Vanity (120cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Sintered Top", "img": "img/6e976e4f54.jpg", "size": "120cm"},
{"code": "LED8060", "name": "Smart Tricolor LED Mirror (80x60cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Tricolor LED", "img": "img/d47528c6ff.jpg", "size": "80x60cm", "price": 5180},
{"code": "LED5070", "name": "Smart Tricolor LED Mirror (50x70cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Tricolor LED", "img": "img/61b7a9dc03.jpg", "size": "50x70cm", "price": 4200},
{"code": "LED6060", "name": "Round/Square Smart LED Mirror (60cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Tricolor LED", "img": "img/c0af5f45c8.jpg", "size": "60cm", "price": 4200},
{"code": "PT5050W", "name": "Framed Accent Mirror (50x50cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "White", "img": "img/5b1ebdd406.jpg", "size": "50x50cm", "price": 1960},
{"code": "PT5050K", "name": "Framed Accent Mirror (50x50cm)", "cat": "Vanity Cabinets & Mirrors", "finish": "Black", "img": "img/413229c5a8.jpg", "size": "50x50cm"},
{"code": "T620-1", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/154613aa12.jpg", "size": "20cm", "price": 770},
{"code": "T630-1", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/154613aa12.jpg", "size": "30cm", "price": 970},
{"code": "T640-1", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/154613aa12.jpg", "size": "40cm", "price": 1240},
{"code": "T660-1", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/154613aa12.jpg", "size": "60cm", "price": 1540},
{"code": "T620-1K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/af81d41dcc.jpg", "size": "20cm", "price": 840},
{"code": "T630-1K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/af81d41dcc.jpg", "size": "30cm", "price": 1100},
{"code": "T640-1K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/af81d41dcc.jpg", "size": "40cm", "price": 1380},
{"code": "T660-1K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/af81d41dcc.jpg", "size": "60cm", "price": 1680},
{"code": "T620-3", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/001e9422a6.jpg", "size": "20cm", "price": 630},
{"code": "T630-3", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/001e9422a6.jpg", "size": "30cm", "price": 840},
{"code": "T640-3", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/001e9422a6.jpg", "size": "40cm", "price": 1050},
{"code": "T660-3", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/001e9422a6.jpg", "size": "60cm", "price": 1260},
{"code": "T620-3K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/f427c30c38.jpg", "size": "20cm", "price": 700},
{"code": "T630-3K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/f427c30c38.jpg", "size": "30cm", "price": 980},
{"code": "T640-3K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/f427c30c38.jpg", "size": "40cm", "price": 1190},
{"code": "T660-3K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/f427c30c38.jpg", "size": "60cm", "price": 1400},
{"code": "T620-4", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/1fca055a9d.jpg", "size": "20cm", "price": 840},
{"code": "T630-4", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/1fca055a9d.jpg", "size": "30cm", "price": 1120},
{"code": "T640-4", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/1fca055a9d.jpg", "size": "40cm", "price": 1400},
{"code": "T660-4", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/1fca055a9d.jpg", "size": "60cm", "price": 1890},
{"code": "T620-4K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/97154ce054.jpg", "size": "20cm", "price": 910},
{"code": "T630-4K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/97154ce054.jpg", "size": "30cm", "price": 1260},
{"code": "T640-4K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/97154ce054.jpg", "size": "40cm", "price": 1540},
{"code": "T660-4K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/97154ce054.jpg", "size": "60cm", "price": 2030},
{"code": "T620-5", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/e868794460.jpg", "size": "20cm", "price": 630},
{"code": "T630-5", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/e868794460.jpg", "size": "30cm", "price": 910},
{"code": "T640-5", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/e868794460.jpg", "size": "40cm", "price": 1120},
{"code": "T660-5", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Brushed", "img": "img/e868794460.jpg", "size": "60cm", "price": 1470},
{"code": "T620-5K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/ea057a5ab9.jpg", "size": "20cm", "price": 770},
{"code": "T630-5K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/ea057a5ab9.jpg", "size": "30cm", "price": 1050},
{"code": "T640-5K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/ea057a5ab9.jpg", "size": "40cm", "price": 1260},
{"code": "T660-5K", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/ea057a5ab9.jpg", "size": "60cm", "price": 1610},
{"code": "525", "name": "Anti-Odour Square Floor Drain", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/352fe40700.jpg", "price": 540},
{"code": "SLD1910", "name": "PTFE Heavy Thread Seal Tape (10g/20g)", "cat": "Drainers & Hoses", "finish": "Standard", "img": "img/b0314c474e.jpg", "size": "10g", "price": 60},
{"code": "SLD1920", "name": "PTFE Heavy Thread Seal Tape (10g/20g)", "cat": "Drainers & Hoses", "finish": "Standard", "img": "img/b0314c474e.jpg", "size": "20g", "price": 80},
{"code": "DHX15H", "name": "Anti-Tangle Bidet Spring Hose", "cat": "Drainers & Hoses", "finish": "Grey", "img": "img/c5e41d3e9c.jpg"},
{"code": "DHX15K", "name": "Anti-Tangle Bidet Spring Hose", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/98f362ee0b.jpg"},
{"code": "PQA503C", "name": "Pressurized Toilet Bidet Sprayer", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/cbd23d169a.jpg", "price": 1820},
{"code": "PQA503H", "name": "Pressurized Toilet Bidet Sprayer", "cat": "Drainers & Hoses", "finish": "Grey", "img": "img/c8748f96d6.jpg", "price": 1820},
{"code": "PQA503K", "name": "Pressurized Toilet Bidet Sprayer", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/5a4d83e161.jpg", "price": 1820},
{"code": "PQA501", "name": "Shatoff Hand Sprayer Set", "cat": "Drainers & Hoses", "finish": "Brushed Nickel", "img": "img/4bed2f7cd7.jpg", "price": 700},
{"code": "PQA501K", "name": "Shatoff Hand Sprayer Set", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/8d995430c5.jpg", "price": 770},
{"code": "PQA505", "name": "Shataff", "cat": "Drainers & Hoses", "finish": "White", "img": "img/465479ca24.jpg", "price": 370},
{"code": "PQA506", "name": "Shataff", "cat": "Drainers & Hoses", "finish": "Brushed Nickel", "img": "img/60f11274a0.jpg", "price": 700},
{"code": "HS511C", "name": "Multi-Mode Hand Shower Wand", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/3d03d7011b.jpg", "price": 700, "best": 1},
{"code": "HS511K", "name": "Hand Shower Set", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/e43e092ac5.jpg", "price": 700, "best": 1},
{"code": "HS512C", "name": "Hand Shower Set", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/96c7d56649.jpg", "price": 730, "best": 1},
{"code": "HS515C", "name": "Hand Shower Set", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/2edf3f01ae.jpg", "price": 980, "best": 1},
{"code": "HS516K", "name": "High-Pressure Hand Shower Wand", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/0c23088822.jpg", "price": 980, "best": 1},
{"code": "RC16C", "name": "Shower Arm", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/dd1afb0658.jpg"},
{"code": "RC16K", "name": "Shower Arm", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/0b94dd8bac.jpg"},
{"code": "RC30C", "name": "Wall Shower Arm (30cm)", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/8bc3f8fa58.jpg", "price": 450},
{"code": "RC30K", "name": "Wall Shower Arm (30cm)", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/b3d27220b5.jpg", "price": 450},
{"code": "D5006", "name": "Rain Shower Head 8-Inch Square", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/1b58acc662.jpg", "size": "8\""},
{"code": "D8006", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/3b16585f96.jpg", "size": "8\""},
{"code": "D8005", "name": "Rain Shower Head 8-Inch Round", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/7d85a669d8.jpg", "size": "8\""},
{"code": "D5012", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/3d50faedb4.jpg", "size": "6\""},
{"code": "D5013", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/76f1ffb613.jpg", "size": "6\""},
{"code": "D5003", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/1f73550fda.jpg", "size": "6\""},
{"code": "D5020", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/06b8155177.jpg", "size": "5\""},
{"code": "D5008", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/1cd02a51b3.jpg", "size": "4\""},
{"code": "D5028", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/3f5ddcdde8.jpg", "size": "4\""},
{"code": "D5039", "name": "Shower Head", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/ae6d37aa6e.jpg", "size": "4\""},
{"code": "RG15C", "name": "Anti-Twist Shower Flexible PVC Hose", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/c95c7f7af6.jpg"},
{"code": "RG15K", "name": "Anti-Twist Shower Flexible PVC Hose", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/4917387237.jpg"},
{"code": "50A", "name": "Flexible Hose (Female)", "cat": "Drainers & Hoses", "finish": "Brushed Nickel", "img": "img/26a2c7f985.jpg", "size": "50cm", "price": 120},
{"code": "60A", "name": "Flexible Hose (Female)", "cat": "Drainers & Hoses", "finish": "Brushed Nickel", "img": "img/26a2c7f985.jpg", "size": "60cm", "price": 140},
{"code": "80A", "name": "Flexible Hose (Female)", "cat": "Drainers & Hoses", "finish": "Brushed Nickel", "img": "img/26a2c7f985.jpg", "size": "80cm", "price": 230},
{"code": "100A", "name": "Flexible Hose (Female)", "cat": "Drainers & Hoses", "finish": "Brushed Nickel", "img": "img/26a2c7f985.jpg", "size": "100cm", "price": 260},
{"code": "50AP/60AP/80AP/100AP", "name": "Flexible Hose (Female)", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/6c45b81fd6.jpg", "size": "50cm / 60cm / 80cm / 100cm"},
{"code": "FH60", "name": "Hot & Cold Flexible Hose", "cat": "Drainers & Hoses", "finish": "", "img": "img/3e590f28a3.jpg", "size": "60cm"},
{"code": "50B", "name": "Flexible Hose", "cat": "Drainers & Hoses", "finish": "", "img": "img/new/c047acacaf.jpg", "size": "50cm", "price": 120},
{"code": "60B", "name": "Flexible Hose", "cat": "Drainers & Hoses", "finish": "", "img": "img/new/c047acacaf.jpg", "size": "60cm", "price": 140},
{"code": "8017C-2", "name": "Shower Mixer", "cat": "Shower Sets", "finish": "Chrome", "img": "img/new/5119201214.jpg", "price": 8260, "best": 1},
{"code": "8017K-2", "name": "Shower Mixer", "cat": "Shower Sets", "finish": "Black", "img": "img/new/5119201214.jpg", "price": 8260, "best": 1},
{"code": "8019C", "name": "Shower Mixer", "cat": "Shower Sets", "finish": "Chrome", "img": "img/new/25401bd403.jpg", "price": 5320, "best": 1},
{"code": "8019H", "name": "Shower Mixer", "cat": "Shower Sets", "finish": "Grey", "img": "img/new/25401bd403.jpg", "price": 5320, "best": 1},
{"code": "8019K", "name": "Shower Mixer", "cat": "Shower Sets", "finish": "Black", "img": "img/new/25401bd403.jpg", "price": 5320, "best": 1},
{"code": "8020", "name": "Shower Mixer", "cat": "Shower Sets", "finish": "", "img": "img/new/8fdb629779.jpg", "price": 7630, "best": 1},
{"code": "LL9013-3G", "name": "Shower Mixer", "cat": "Concealed Mixers", "finish": "Gold", "img": "img/new/67098deab2.jpg", "price": 11060, "best": 1},
{"code": "LL9019-4C", "name": "Shower Panel (Screen)", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/new/de114a26eb.jpg", "price": 14000, "best": 1},
{"code": "LL9019-4K", "name": "Shower Panel (Screen)", "cat": "Concealed Mixers", "finish": "Black", "img": "img/new/de114a26eb.jpg", "price": 14000, "best": 1},
{"code": "LL9020-5C", "name": "Shower Panel (Screen)", "cat": "Concealed Mixers", "finish": "Chrome", "img": "img/new/fad5c499dd.jpg", "price": 15400, "best": 1},
{"code": "LL9020-5K", "name": "Shower Panel (Screen)", "cat": "Concealed Mixers", "finish": "Black", "img": "img/new/fad5c499dd.jpg", "price": 15400, "best": 1},
{"code": "POLE120C", "name": "Shower Pole", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/new/95de864eec.jpg", "size": "120cm", "price": 840},
{"code": "POLE120K", "name": "Shower Pole", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/new/70a3ae423b.jpg", "size": "120cm", "price": 840},
{"code": "9004", "name": "Angle Valve", "cat": "Angle Valves & Filters", "finish": "", "img": "img/new/23b1de9884.jpg", "price": 1190},
{"code": "9016C", "name": "Shower Exchanger (Diverter)", "cat": "Angle Valves & Filters", "finish": "Chrome", "img": "img/new/07258ad1e9.jpg", "price": 630},
{"code": "9016K", "name": "Shower Exchanger (Diverter)", "cat": "Angle Valves & Filters", "finish": "Black", "img": "img/new/e0e9f0e70e.jpg", "price": 630},
{"code": "9006", "name": "Angle Valve", "cat": "Angle Valves & Filters", "finish": "", "img": "img/new/a859634a8b.jpg", "price": 420},
{"code": "3004C", "name": "Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "Chrome", "img": "img/new/4fe871bfe0.jpg", "price": 1470, "best": 1},
{"code": "3006", "name": "Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "", "img": "img/new/38c9edafb7.jpg", "price": 1400, "best": 1},
{"code": "3008", "name": "Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "", "img": "img/new/ee8ca81b3e.jpg", "price": 1400, "best": 1},
{"code": "3017H", "name": "Basin Mixer", "cat": "Basin Mixers & Taps", "finish": "Grey", "img": "img/new/640fb1fb22.jpg", "price": 1820, "best": 1},
{"code": "6023C", "name": "Kitchen Sink Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "Chrome", "img": "img/new/a360b438b7.jpg", "price": 2520, "best": 1},
{"code": "6013", "name": "Pull-Out Kitchen Sink Mixer", "cat": "Kitchen Mixers & Sink Taps", "finish": "", "img": "img/new/67c93c0a5a.jpg", "price": 3500, "best": 1},
{"code": "PQA506K", "name": "Bidet Sprayer (Shattaf)", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/new/00a9647e52.jpg", "price": 700},
{"code": "GJS6607C", "name": "Tissue Holder", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/e22ab8721e.jpg", "price": 420},
{"code": "GJ7900C", "name": "Bathroom Accessories Set", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/77c6db9c56.jpg", "price": 2800},
{"code": "7546H", "name": "Waterfall Sink", "cat": "Kitchen Sinks", "finish": "Grey", "img": "img/new/8c3472bba5.jpg", "price": 21000},
{"code": "12050K", "name": "Double Sink", "cat": "Kitchen Sinks", "finish": "Black", "img": "img/new/4c986f3cc4.jpg", "price": 16800},
{"code": "HS412C", "name": "Shower Head Set", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/new/0e98f78d04.jpg", "price": 1540, "best": 1},
{"code": "HS413K", "name": "Shower Head Set", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/new/b63e16e9bb.jpg", "price": 1400, "best": 1},
{"code": "HS513C", "name": "Hand Shower Set", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/new/f21b4999cd.jpg", "price": 770, "best": 1},
{"code": "HS514C", "name": "Hand Shower Set", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/new/783efc3816.jpg", "price": 980, "best": 1},
{"code": "HS517K", "name": "Hand Shower Set", "cat": "Drainers & Hoses", "finish": "Black", "img": "img/new/36d9078bcf.jpg", "price": 490, "best": 1},
{"code": "HS519C", "name": "Hand Shower Set", "cat": "Drainers & Hoses", "finish": "Chrome", "img": "img/new/93a15ec96d.jpg", "price": 490, "best": 1},
{"code": "WF12A", "name": "Water Filter Housing", "cat": "Angle Valves & Filters", "finish": "", "img": "img/new/f7a4166c62.jpg", "size": "3/4\"", "price": 2100},
{"code": "WF12B", "name": "Water Filter Housing", "cat": "Angle Valves & Filters", "finish": "", "img": "img/new/f7a4166c62.jpg", "size": "1\"", "price": 2100},
{"code": "JX12050", "name": "Drainer", "cat": "Kitchen Sinks", "finish": "", "img": "img/new/3066437f62.jpg", "price": 680},
{"code": "JX12050C", "name": "Drainer", "cat": "Kitchen Sinks", "finish": "Chrome", "img": "img/new/b099bf4927.jpg", "price": 680},
{"code": "JX12050K", "name": "Drainer", "cat": "Kitchen Sinks", "finish": "Black", "img": "img/new/ab47088999.jpg", "price": 680},
{"code": "MT07-B", "name": "Toilet Seat", "cat": "Toilets & Sanitary Ware", "finish": "", "img": "img/new/c85c24bfa7.jpg", "price": 840},
{"code": "MT07-T", "name": "Toilet Seat", "cat": "Toilets & Sanitary Ware", "finish": "", "img": "img/new/c85c24bfa7.jpg", "price": 840},
{"code": "MT69-B", "name": "Toilet Seat", "cat": "Toilets & Sanitary Ware", "finish": "", "img": "img/new/8870f8fb22.jpg", "price": 840},
{"code": "MT69-T", "name": "Toilet Seat", "cat": "Toilets & Sanitary Ware", "finish": "", "img": "img/new/8870f8fb22.jpg", "price": 840},
{"code": "MT49-B", "name": "Toilet Seat", "cat": "Toilets & Sanitary Ware", "finish": "", "img": "img/new/e84b9a8488.jpg", "price": 840},
{"code": "MT49-T", "name": "Toilet Seat", "cat": "Toilets & Sanitary Ware", "finish": "", "img": "img/new/e84b9a8488.jpg", "price": 840},
{"code": "12050-1LS", "name": "Double Sink", "cat": "Kitchen Sinks", "finish": "", "img": "img/new/67b7a3fe51.jpg", "price": 6720},
{"code": "SSWA01", "name": "Cup Washer", "cat": "Kitchen Sinks", "finish": "", "img": "img/new/aaade027f1.jpg", "price": 910},
{"code": "T620-2", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "", "img": "", "size": "20cm", "price": 770},
{"code": "T630-2", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "", "img": "img/new/ecfe3488ef.jpg", "size": "30cm", "price": 970},
{"code": "T640-2", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "", "img": "img/new/ecfe3488ef.jpg", "size": "40cm", "price": 1240},
{"code": "T660-2", "name": "Floor Drainer", "cat": "Drainers & Hoses", "finish": "", "img": "", "size": "60cm", "price": 1540},
{"code": "1016C-4", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/3ba59be45b.jpg", "size": "4 hooks", "price": 380},
{"code": "1016C-5", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/a246bbced0.jpg", "size": "5 hooks", "price": 450},
{"code": "1022C-4", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/c25db35b3d.jpg", "size": "4 hooks", "price": 350},
{"code": "1022C-5", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/352b52dc47.jpg", "size": "5 hooks", "price": 420},
{"code": "GJ1053C-4", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/495e171caf.jpg", "size": "4 hooks", "price": 350},
{"code": "GJ1053C-5", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Chrome", "img": "img/new/096b39df08.jpg", "size": "5 hooks", "price": 420},
{"code": "GJ1053K-4", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/new/bc1a931c6d.jpg", "size": "4 hooks", "price": 380},
{"code": "GJ1053K-5", "name": "Hooks", "cat": "Bathroom Accessories", "finish": "Black", "img": "img/new/0a2e137a01.jpg", "size": "5 hooks", "price": 450},
{"code": "3169-60", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/cd56eae8bd.jpg", "size": "60cm", "price": 23800},
{"code": "1030-50", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/c72044030b.jpg", "size": "50cm", "price": 15400},
{"code": "3187-80Y", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/31d7395086.jpg", "size": "80cm", "price": 33600},
{"code": "603-80", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/8ed33bd896.jpg", "size": "80cm", "price": 28000},
{"code": "605-60", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/9bbcb40335.jpg", "size": "60cm", "price": 21000},
{"code": "605-80", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/9bbcb40335.jpg", "size": "80cm", "price": 25200},
{"code": "608-60", "name": "Vanity Cabinet", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/ba6a13d29b.jpg", "size": "60cm", "price": 21000},
{"code": "PT5070W", "name": "Mirror", "cat": "Vanity Cabinets & Mirrors", "finish": "", "img": "img/new/61bb3a964a.jpg", "price": 2100}
];
